# Generated by Django 4.2.19 on 2025-02-27 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('user', models.CharField(max_length=50, verbose_name='user')),
                ('book', models.CharField(max_length=50, verbose_name='book')),
                ('quantity', models.PositiveIntegerField(verbose_name='quantity')),
                ('price', models.IntegerField(verbose_name='price')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='order_date')),
            ],
        ),
    ]
